name: CLIP1
path: openai/clip-vit-base-patch32
processor: openai/clip-vit-base-patch32
load: ViT-B/32

save_dir: models/CLIP1

train:
  epochs: 30

optimizer:
  adam:
    lr: 5.e-5
    betas: [0.9,0.98]
    eps: 1.e-6
    wdec: 0.2
